version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    ports:
      - "8080:9000"  # API port
      - "8880:8880"  # Console port
    volumes:
      - ./minio_data:/data
      - ./config:/root/.minio"
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minioadmin      # Change this to your desired admin username
      MINIO_ROOT_PASSWORD: xkwl8888!!!  # Change this to your desired admin password
    command: server --console-address ":8880" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data: